### ISSUE TITLE
apa.polya error while annotating

### ISSUE THREAD

**Issue by borshago** [grexor/apa#13]
Hi! I'm trying to run the apa pipeline post-alignment and I've run into some trouble. I'm using the apa release v1.1 and the pybio release v1.2.

I'm testing the apa pipeline with 4 BAM-files downloaded from expressrna: 20150203_ina_e1_m1.bam, 20150203_ina_e2_m1.bam, 20150203_ina_e3_m1.bam, 20150203_ina_e4_m1.bam. I've renamed the library to elib, so it corresponds to the configurations described in the manual (apa_python.rst). I've created the genome with pybio's script hg19.download.ensembl75.sh.

After running the command "python bin/apa.polya -poly_id elib" I get the error "ValueError: too many values to unpack" from pybio.genomes.annotate. The complete output is here:

> /scratch/project_2001351/Daniel/CONDA/ENVS/apa_py/lib/python2.7/site-packages/apa/data.apa/elib/e1/m1/elib_e1_m1.tail.bed
loading: /scratch/project_2001351/Daniel/CONDA/ENVS/apa_py/lib/python2.7/site-packages/apa/data.apa/elib/e1/m1/elib_e1_m1.tail.bed
1: elib 1 elib True 1.50M
/scratch/project_2001351/Daniel/CONDA/ENVS/apa_py/lib/python2.7/site-packages/apa/data.apa/elib/e2/m1/elib_e2_m1.tail.bed
loading: /scratch/project_2001351/Daniel/CONDA/ENVS/apa_py/lib/python2.7/site-packages/apa/data.apa/elib/e2/m1/elib_e2_m1.tail.bed
2: elib 2 elib True 3.32M
/scratch/project_2001351/Daniel/CONDA/ENVS/apa_py/lib/python2.7/site-packages/apa/data.apa/elib/e3/m1/elib_e3_m1.tail.bed
loading: /scratch/project_2001351/Daniel/CONDA/ENVS/apa_py/lib/python2.7/site-packages/apa/data.apa/elib/e3/m1/elib_e3_m1.tail.bed
3: elib 3 elib True 5.07M
/scratch/project_2001351/Daniel/CONDA/ENVS/apa_py/lib/python2.7/site-packages/apa/data.apa/elib/e4/m1/elib_e4_m1.tail.bed
loading: /scratch/project_2001351/Daniel/CONDA/ENVS/apa_py/lib/python2.7/site-packages/apa/data.apa/elib/e4/m1/elib_e4_m1.tail.bed
4: elib 4 elib True 6.58M
filtering: +GL000219.1 (min distance = 125nt)
filtering: -GL000219.1 (min distance = 125nt)
filtering: +GL000241.1 (min distance = 125nt)
filtering: -GL000192.1 (min distance = 125nt)
filtering: -GL000191.1 (min distance = 125nt)
filtering: -GL000238.1 (min distance = 125nt)
filtering: +GL000194.1 (min distance = 125nt)
filtering: -GL000194.1 (min distance = 125nt)
filtering: -GL000211.1 (min distance = 125nt)
filtering: +GL000195.1 (min distance = 125nt)
filtering: -GL000195.1 (min distance = 125nt)
filtering: +GL000212.1 (min distance = 125nt)
filtering: -GL000212.1 (min distance = 125nt)
filtering: +20 (min distance = 125nt)
filtering: -20 (min distance = 125nt)
filtering: +21 (min distance = 125nt)
filtering: -21 (min distance = 125nt)
filtering: +22 (min distance = 125nt)
filtering: -22 (min distance = 125nt)
filtering: -GL000196.1 (min distance = 125nt)
filtering: +GL000235.1 (min distance = 125nt)
filtering: +GL000205.1 (min distance = 125nt)
filtering: -GL000205.1 (min distance = 125nt)
filtering: +1 (min distance = 125nt)
filtering: -1 (min distance = 125nt)
filtering: +3 (min distance = 125nt)
filtering: -3 (min distance = 125nt)
filtering: +2 (min distance = 125nt)
filtering: -2 (min distance = 125nt)
filtering: +5 (min distance = 125nt)
filtering: -5 (min distance = 125nt)
filtering: +4 (min distance = 125nt)
filtering: -4 (min distance = 125nt)
filtering: +7 (min distance = 125nt)
filtering: -7 (min distance = 125nt)
filtering: +6 (min distance = 125nt)
filtering: -6 (min distance = 125nt)
filtering: +9 (min distance = 125nt)
filtering: -9 (min distance = 125nt)
filtering: +8 (min distance = 125nt)
filtering: -8 (min distance = 125nt)
filtering: -GL000199.1 (min distance = 125nt)
filtering: -GL000214.1 (min distance = 125nt)
filtering: +GL000224.1 (min distance = 125nt)
filtering: +GL000220.1 (min distance = 125nt)
filtering: -GL000220.1 (min distance = 125nt)
filtering: +GL000222.1 (min distance = 125nt)
filtering: -GL000222.1 (min distance = 125nt)
filtering: +GL000221.1 (min distance = 125nt)
filtering: -GL000221.1 (min distance = 125nt)
filtering: +GL000223.1 (min distance = 125nt)
filtering: +GL000229.1 (min distance = 125nt)
filtering: -GL000229.1 (min distance = 125nt)
filtering: -GL000247.1 (min distance = 125nt)
filtering: +Y (min distance = 125nt)
filtering: -Y (min distance = 125nt)
filtering: +X (min distance = 125nt)
filtering: -X (min distance = 125nt)
filtering: -GL000232.1 (min distance = 125nt)
filtering: +11 (min distance = 125nt)
filtering: -11 (min distance = 125nt)
filtering: +10 (min distance = 125nt)
filtering: -10 (min distance = 125nt)
filtering: +13 (min distance = 125nt)
filtering: -13 (min distance = 125nt)
filtering: +12 (min distance = 125nt)
filtering: -12 (min distance = 125nt)
filtering: +15 (min distance = 125nt)
filtering: -15 (min distance = 125nt)
filtering: +14 (min distance = 125nt)
filtering: -14 (min distance = 125nt)
filtering: +17 (min distance = 125nt)
filtering: -17 (min distance = 125nt)
filtering: +16 (min distance = 125nt)
filtering: -16 (min distance = 125nt)
filtering: +19 (min distance = 125nt)
filtering: -19 (min distance = 125nt)
filtering: +18 (min distance = 125nt)
filtering: -18 (min distance = 125nt)
filtering: -GL000217.1 (min distance = 125nt)
filtering: -GL000216.1 (min distance = 125nt)
filtering: +MT (min distance = 125nt)
filtering: -MT (min distance = 125nt)
filtering: +GL000225.1 (min distance = 125nt)
filtering: -GL000225.1 (min distance = 125nt)
filtering: +GL000218.1 (min distance = 125nt)
filtering: -GL000218.1 (min distance = 125nt)
save : /scratch/project_2001351/Daniel/CONDA/ENVS/apa_py/lib/python2.7/site-packages/apa/data.polya/elib.temp, format : bed
hg19: loading genome
Traceback (most recent call last):
  File "bin/apa.polya", line 12, in <module>
    apa.polya.process(args.poly_id, map_id=args.map_id)
  File "/scratch/project_2001351/Daniel/CONDA/ENVS/apa_py/lib/python2.7/site-packages/apa/polya/__init__.py", line 95, in process
    annotate(poly_id)
  File "/scratch/project_2001351/Daniel/CONDA/ENVS/apa_py/lib/python2.7/site-packages/apa/polya/__init__.py", line 130, in annotate
    gid_up, gid, gid_down, gid_interval = annotate_position(species, chr, strand, pos)
  File "/scratch/project_2001351/Daniel/CONDA/ENVS/apa_py/lib/python2.7/site-packages/apa/polya/__init__.py", line 359, in annotate_position
    gid_up, gid, gid_down, gid_interval = pybio.genomes.annotate(species, chr, strand, pos)
ValueError: too many values to unpack

Any ideas how to solve this?

**Comment by borshago** [comment]
I realized that pybio 1.2 is not compatible with apa 1.1. The problem did not occur when using pybio 1.1.
