### ISSUE TITLE
Pybio Github reorganization has broken the paths for apa example

### ISSUE THREAD

**Issue by rbarbieri86** [grexor/apa#23]
Hello, I am trying to run the apa example but I run into this issue:

bash run_apauser.sh
apauser@groovy:~$ bash apa/docker/example.sh
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AttributeError: module 'pybio' has no attribute 'path'
apa/docker/example.sh: line 6: cd: /home/apauser/pybio/genomes: No such file or directory
apa/docker/example.sh: line 7: ./hg38chr22.download.ensembl98.sh: No such file or directory
mkdir: cannot create directory ‘/home/apauser/data/libs’: File exists
mkdir: cannot create directory ‘/home/apauser/data/comps’: File exists
mkdir: cannot create directory ‘/home/apauser/data/polya’: File exists
mkdir: cannot create directory ‘/home/apauser/data/libs/example’: File exists
mkdir: cannot create directory ‘/home/apauser/data/comps/example’: File exists
mkdir: cannot create directory ‘e1’: File exists

I have already modified the Dockerfile to point to '/home/apauser/pybio/pybio/' as the git clone now produces a different folder architecture but it looks like example.sh still looks in the wrong place.

Additionally the files needes for the example can't be found at the indicated URLs:

--2023-04-24 10:20:02--  https://expressrna.org/share/data/example/e1/example_e1.fastq.gz
Resolving expressrna.org (expressrna.org)... 130.60.24.217
Connecting to expressrna.org (expressrna.org)|130.60.24.217|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-24 10:20:02 ERROR 404: Not Found.

mkdir: cannot create directory ‘e2’: File exists
--2023-04-24 10:20:02--  https://expressrna.org/share/data/example/e2/example_e2.fastq.gz
Resolving expressrna.org (expressrna.org)... 130.60.24.217
Connecting to expressrna.org (expressrna.org)|130.60.24.217|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-24 10:20:02 ERROR 404: Not Found.

mkdir: cannot create directory ‘e3’: File exists
--2023-04-24 10:20:02--  https://expressrna.org/share/data/example/e3/example_e3.fastq.gz
Resolving expressrna.org (expressrna.org)... 130.60.24.217
Connecting to expressrna.org (expressrna.org)|130.60.24.217|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-24 10:20:02 ERROR 404: Not Found.

mkdir: cannot create directory ‘e4’: File exists
--2023-04-24 10:20:02--  https://expressrna.org/share/data/example/e4/example_e4.fastq.gz
Resolving expressrna.org (expressrna.org)... 130.60.24.217
Connecting to expressrna.org (expressrna.org)|130.60.24.217|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-24 10:20:02 ERROR 404: Not Found.

mkdir: cannot create directory ‘e5’: File exists
--2023-04-24 10:20:02--  https://expressrna.org/share/data/example/e5/example_e5.fastq.gz
Resolving expressrna.org (expressrna.org)... 130.60.24.217
Connecting to expressrna.org (expressrna.org)|130.60.24.217|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-24 10:20:03 ERROR 404: Not Found.

mkdir: cannot create directory ‘e6’: File exists
--2023-04-24 10:20:03--  https://expressrna.org/share/data/example/e6/example_e6.fastq.gz
Resolving expressrna.org (expressrna.org)... 130.60.24.217
Connecting to expressrna.org (expressrna.org)|130.60.24.217|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-24 10:20:03 ERROR 404: Not Found.

--2023-04-24 10:20:03--  https://expressrna.org/share/data/example/example.config
Resolving expressrna.org (expressrna.org)... 130.60.24.217
Connecting to expressrna.org (expressrna.org)|130.60.24.217|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-24 10:20:03 ERROR 404: Not Found.

--2023-04-24 10:20:03--  https://expressrna.org/share/data/example/annotation.tab
Resolving expressrna.org (expressrna.org)... 130.60.24.217
Connecting to expressrna.org (expressrna.org)|130.60.24.217|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-24 10:20:03 ERROR 404: Not Found.

--2023-04-24 10:20:03--  https://expressrna.org/share/comps/example/example.config
Resolving expressrna.org (expressrna.org)... 130.60.24.217
Connecting to expressrna.org (expressrna.org)|130.60.24.217|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 370
Saving to: ‘/home/apauser/data/comps/example/example.config’

Finally, a quick question: I should be able to use already aligned BAMs in the apa pipeline, is that right?

Thank you very much in advance!

**Comment by grexor** [comment]
Thank you for testing apa and for opening the issue.

I restored now the example URLs on the server, so data download should work.

However, pybio has undergone changes (for the better I hope:), so to download the human genome one now needs to do:

```
pip install pybio
pybio config # this will allow you to decide where genome files will be stored (default ~/genomes)
pybio genome homo_sapiens # this will download the human genome and make STAR index (if STAR is available)
```

Hope this helps for now, feel free to write more.

Cheers,
Gregor

**Comment by grexor** [comment]
Another thingy:

Instead of this:

`echo "pybio.path.genomes_folder='/home/apauser/pybio/genomes/data/genomes'" >> /home/apauser/pybio/config/config.txt`

You would now do this:

`pybio config /home/apauser/pybio/genomes/data/genomes`

**Comment by rbarbieri86** [comment]
Thanks a lot and sorry for the late-ish reply. I will try modifying the Dockerfile and hopefully solve this.

A quick question: would it be possible to download the genome without running STAR? It is included in the Dockerfile of course but I was planning to feed APA with already aligned BAM files (with STAR) as I don't have enough RAM on my current machine.
It would be nice if that would work.

**Comment by grexor** [comment]
Yes possible, with this:

`pybio genome homo_sapiens --nostar --nosalmon`

Hope this helps, Gregor

**Comment by rbarbieri86** [comment]
Hello, I have modified the Dockerfile (pybio section) as follows:

RUN pip install pybio
RUN mkdir ~/pybio/
RUN mkdir ~/pybio/genomes/
RUN mkdir ~/pybio/genomes/data/
RUN ln -s /home/apauser/data /home/apauser/pybio/genomes/data
RUN pybio config /home/apauser/pybio/genomes/data/genomes
RUN echo "apa.path.data_folder='/home/apauser/data/libs'" >> /home/apauser/apa/config/config.txt
RUN echo "apa.path.comps_folder='/home/apauser/data/comps'" >> /home/apauser/apa/config/config.txt
RUN echo "apa.path.polya_folder='/home/apauser/data/polya'" >> /home/apauser/apa/config/config.txt
RUN pybio genome homo_sapiens --nostar --nosalmon

However it seems Docker doesn't correctly locate pybio:
> [50/54] RUN pybio config /home/apauser/pybio/genomes/data/genomes:
#0 0.484 /bin/sh: 1: pybio: not found
------
Dockerfile:74
--------------------
  72 |     RUN ln -s /home/apauser/data /home/apauser/pybio/genomes/data
  73 |     #RUN echo "pybio.path.genomes_folder='/home/apauser/pybio/pybio/genomes/data/genomes'" >> /home/apauser/pybio/pybio/config/config.txt
  74 | >>> RUN pybio config /home/apauser/pybio/genomes/data/genomes
  75 |     RUN echo "apa.path.data_folder='/home/apauser/data/libs'" >> /home/apauser/apa/config/config.txt
  76 |     RUN echo "apa.path.comps_folder='/home/apauser/data/comps'" >> /home/apauser/apa/config/config.txt
--------------------
ERROR: failed to solve: process "/bin/sh -c pybio config /home/apauser/pybio/genomes/data/genomes" did not complete successfully: exit code: 127

Pybio installs fine and the config command works as expected on my machine (Ubuntu on WSL), so maybe I should add a line to the Dockerfile to fix this. Also can I assume it is not necessary anymore to add the libs, comps and polya folders manually?

Thanks in advance!

**Comment by grexor** [comment]
Could you try: `pip3 install pybio`?

**Comment by rbarbieri86** [comment]
Tried right now, same error. I can share the whole Dockerfile if needed, I had to add a few libraries installations to make the previous steps work.

**Comment by grexor** [comment]
Yes please, I can also have a look.

**Comment by rbarbieri86** [comment]
Ok, pasted below:
FROM groovy

MAINTAINER Gregor Rot <gregor.rot@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Zurich

USER root
RUN apt update
RUN apt-get install -y vim
RUN apt-get install -y python3
RUN apt-get install -y git
RUN apt-get install -y python3-pip
RUN apt-get install -y rna-star
RUN apt-get install -y samtools
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y libxml2-dev
RUN apt-get install -y libssl-dev
RUN apt-get install -y pkg-config
RUN apt-get install -y libfreetype6-dev
RUN wget -q -O /tmp/libicu66.deb http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2_amd64.deb \
        && dpkg -i /tmp/libicu66.deb \
        && rm /tmp/libicu66.deb
RUN pip3 install pysam
RUN pip3 install numpy
RUN pip3 install freetype-py==2.3
RUN pip3 install matplotlib==3.2
RUN pip3 install regex
RUN pip3 install pandas
RUN pip3 install HTSeq

# R
RUN apt-get install -y software-properties-common
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
RUN add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
RUN apt install -y r-base r-base-core r-recommended r-base-dev
RUN R -e 'install.packages("BiocManager")'
RUN R -e 'BiocManager::install("edgeR")'
RUN R -e 'BiocManager::install("DEXSeq")'
RUN R -e 'install.packages("data.table")'

# apauser
RUN useradd -m -d /home/apauser apauser
ADD . /home/apauser/apa
RUN chown -R apauser.apauser /home/apauser

USER apauser
WORKDIR /home/apauser
RUN mkdir ~/data
RUN echo "alias python='python3'" >> ~/.bashrc

# salmon
RUN mkdir ~/software
RUN wget https://github.com/COMBINE-lab/salmon/releases/download/v1.4.0/salmon-1.4.0_linux_x86_64.tar.gz -O ~/software/salmon.tgz
WORKDIR /home/apauser/software
RUN tar xfz salmon.tgz
RUN rm salmon.tgz
RUN mv salmon-latest_linux_x86_64/ salmon

# paths
RUN echo "export PATH=$PATH:/home/apauser/apa/bin:/home/apauser/pybio/pybio/bin:~/software/salmon/bin" >> ~/.bashrc
RUN echo "export PYTHONPATH=$PYTHONPATH:/home/apauser" >> ~/.bashrc

WORKDIR /home/apauser

# pybio
RUN pip3 install pybio
RUN mkdir ~/pybio/
RUN mkdir ~/pybio/genomes/
RUN mkdir ~/pybio/genomes/data/
RUN ln -s /home/apauser/data /home/apauser/pybio/genomes/data
RUN pybio config /home/apauser/pybio/genomes/data/genomes
RUN echo "apa.path.data_folder='/home/apauser/data/libs'" >> /home/apauser/apa/config/config.txt
RUN echo "apa.path.comps_folder='/home/apauser/data/comps'" >> /home/apauser/apa/config/config.txt
RUN echo "apa.path.polya_folder='/home/apauser/data/polya'" >> /home/apauser/apa/config/config.txt
RUN pybio genome homo_sapiens --nostar --nosalmon

**Comment by grexor** [comment]
Perhaps the Dockerfile needs an update, for me this works:

```
FROM ubuntu:21.04
USER root
RUN apt-get -y update
RUN apt-get install -y vim python3 git python3-pip libbz2-dev liblzma-dev wget
RUN pip3 install pybio
```

Something in this direction?

**Comment by grexor** [comment]
@rbarbieri86 would that help?

**Comment by rbarbieri86** [comment]
I can give it a try. I am using Ubuntu 22.04 so I will put that.
I will let you know if it works, thanks for the pointers.

PS: Should I remove the "ENV" lines? Sorry I am pretty new to Docker.

**Comment by rbarbieri86** [comment]
I have tried updating the Dockerfile:
FROM ubuntu:22.04

MAINTAINER Gregor Rot <gregor.rot@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Zurich

USER root
RUN apt-get -y update
RUN apt-get install -y vim python3 git python3-pip libbz2-dev liblzma-dev wget
RUN apt-get install -y git
RUN apt-get install -y python3-pip
RUN apt-get install -y rna-star
RUN apt-get install -y samtools
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y libxml2-dev
RUN apt-get install -y libssl-dev
RUN apt-get install -y pkg-config
RUN apt-get install -y libfreetype6-dev
RUN apt-get install -y tzdata
RUN wget -q -O /tmp/libicu66.deb http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2_amd64.deb \
        && dpkg -i /tmp/libicu66.deb \
        && rm /tmp/libicu66.deb
RUN pip3 install pysam
RUN pip3 install numpy
RUN pip3 install freetype-py==2.3
RUN pip3 install matplotlib==3.2
RUN pip3 install regex
RUN pip3 install pandas
RUN pip3 install HTSeq

# R
RUN apt-get install -y software-properties-common
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
RUN add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
RUN apt install -y r-base r-base-core r-recommended r-base-dev
RUN R -e 'install.packages("BiocManager")'
RUN R -e 'BiocManager::install("edgeR")'
RUN R -e 'BiocManager::install("DEXSeq")'
RUN R -e 'install.packages("data.table")'

# apauser
RUN useradd -m -d /home/apauser apauser
ADD . /home/apauser/apa
RUN chown -R apauser.apauser /home/apauser

USER apauser
WORKDIR /home/apauser
RUN mkdir ~/data
RUN echo "alias python='python3'" >> ~/.bashrc

# salmon
RUN mkdir ~/software
RUN wget https://github.com/COMBINE-lab/salmon/releases/download/v1.4.0/salmon-1.4.0_linux_x86_64.tar.gz -O ~/software/salmon.tgz
WORKDIR /home/apauser/software
RUN tar xfz salmon.tgz
RUN rm salmon.tgz
RUN mv salmon-latest_linux_x86_64/ salmon

# paths
RUN echo "export PATH=$PATH:/home/apauser/apa/bin:/home/apauser/pybio/pybio/bin:~/software/salmon/bin" >> ~/.bashrc
RUN echo "export PYTHONPATH=$PYTHONPATH:/home/apauser" >> ~/.bashrc

WORKDIR /home/apauser

# pybio
#RUN git clone https://github.com/grexor/pybio.git
RUN pip3 install pybio
RUN mkdir ~/pybio/
RUN mkdir ~/pybio/genomes/
RUN mkdir ~/pybio/genomes/data/
RUN ln -s /home/apauser/data /home/apauser/pybio/genomes/data
#RUN echo "pybio.path.genomes_folder='/home/apauser/pybio/pybio/genomes/data/genomes'" >> /home/apauser/pybio/pybio/config/config.txt
RUN pybio config /home/apauser/pybio/genomes/data/genomes
RUN echo "apa.path.data_folder='/home/apauser/data/libs'" >> /home/apauser/apa/config/config.txt
RUN echo "apa.path.comps_folder='/home/apauser/data/comps'" >> /home/apauser/apa/config/config.txt
RUN echo "apa.path.polya_folder='/home/apauser/data/polya'" >> /home/apauser/apa/config/config.txt
RUN pybio genome homo_sapiens --nostar --nosalmon

However there is a new error:
> [50/54] RUN pybio config /home/apauser/pybio/genomes/data/genomes:
#0 0.428 /bin/sh: 1: pybio: not found
------
Dockerfile:74
--------------------
  72 |     RUN ln -s /home/apauser/data /home/apauser/pybio/genomes/data
  73 |     #RUN echo "pybio.path.genomes_folder='/home/apauser/pybio/pybio/genomes/data/genomes'" >> /home/apauser/pybio/pybio/config/config.txt
  74 | >>> RUN pybio config /home/apauser/pybio/genomes/data/genomes
  75 |     RUN echo "apa.path.data_folder='/home/apauser/data/libs'" >> /home/apauser/apa/config/config.txt
  76 |     RUN echo "apa.path.comps_folder='/home/apauser/data/comps'" >> /home/apauser/apa/config/config.txt
--------------------
ERROR: failed to solve: process "/bin/sh -c pybio config /home/apauser/pybio/genomes/data/genomes" did not complete successfully: exit code: 127

Maybe I should modify how the ~/pybio/ folder is added to PATH?

**Comment by grexor** [comment]
ok found out what the problem is: if you install pybio under apauser, then for some reason the script path is not added, you should add this:

`ENV PATH "$PATH:/home/apauser/.local/bin"`

Then it should work. Another alternative is to use virtualenv for example. Hope this helps

**Comment by rbarbieri86** [comment]
Adding the line "ENV PATH "$PATH:/home/apauser/.local/bin" let build.sh finish without errors, thanks a lot :)
I will test out the example data ASAP

**Comment by rbarbieri86** [comment]
Hello again, the example.sh script starts regularly but can't complete the required task due to permission issues:
apauser@groovy:~/apa$ bash docker/example.sh
docker/example.sh: line 7: ./hg38chr22.download.ensembl98.sh: No such file or directory
mkdir: cannot create directory '/home/apauser/data/libs': File exists
mkdir: cannot create directory '/home/apauser/data/comps': File exists
mkdir: cannot create directory '/home/apauser/data/polya': File exists
mkdir: cannot create directory '/home/apauser/data/libs/example': File exists
mkdir: cannot create directory '/home/apauser/data/comps/example': File exists
mkdir: cannot create directory 'e1': File exists
e1/example_e1.fastq.gz: Permission denied
mkdir: cannot create directory 'e2': File exists
e2/example_e2.fastq.gz: Permission denied
mkdir: cannot create directory 'e3': File exists
e3/example_e3.fastq.gz: Permission denied
mkdir: cannot create directory 'e4': File exists
e4/example_e4.fastq.gz: Permission denied
mkdir: cannot create directory 'e5': File exists
e5/example_e5.fastq.gz: Permission denied
mkdir: cannot create directory 'e6': File exists
e6/example_e6.fastq.gz: Permission denied
example.config: Permission denied
annotation.tab: Permission denied
/home/apauser/data/comps/example/example.config: Permission denied
Traceback (most recent call last):
  File "/home/apauser/apa/bin/apa.polya.makeconfig", line 11, in <module>
    apa.polya.make_config(args.lib_id)
  File "/home/apauser/apa/polya/__init__.py", line 46, in make_config
    f = open(os.path.join(apa.path.polya_folder, "%s.config" % lib_id), "wt")
PermissionError: [Errno 13] Permission denied: '/home/apauser/data/polya/example.config'
Traceback (most recent call last):
  File "/home/apauser/apa/bin/apa.polya", line 13, in <module>
    apa.polya.process(args.poly_id, map_id=args.map_id, min_distance=args.min_distance)
  File "/home/apauser/apa/polya/__init__.py", line 65, in process
    species = get_species(poly_id)
  File "/home/apauser/apa/polya/__init__.py", line 27, in get_species
    if poly_id in pybio.genomes.genomes_list():
AttributeError: module 'pybio' has no attribute 'genomes'
cp: cannot stat '/home/apauser/data/polya/example.bed.gz': No such file or directory
Traceback (most recent call last):
  File "/home/apauser/apa/bin/apa.bed.gene_expression", line 15, in <module>
    lib.save()
  File "/home/apauser/apa/annotation/__init__.py", line 198, in save
    f = open(filename, "wt")
PermissionError: [Errno 13] Permission denied: '/home/apauser/data/libs/example/example.config'
Traceback (most recent call last):
  File "/home/apauser/apa/bin/apa.comps", line 11, in <module>
    apa.comps.process_comps(args.comps_id, map_id=args.map_id)
  File "/home/apauser/apa/comps/__init__.py", line 298, in process_comps
    comps = Comps(comps_id) # study data
  File "/home/apauser/apa/comps/__init__.py", line 60, in __init__
    self.read_comps(comps_id)
  File "/home/apauser/apa/comps/__init__.py", line 233, in read_comps
    species.add(apa.annotation.libs[lib_id].experiments[exp_id]["map_to"])
KeyError: 6


Should I try to use sudo? I guess the problem lies in the fact I am using Docker inside a WSL environment.
